require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommentsController do

  # This should return the minimal set of attributes required to create a valid
  # Comment. As you add validations to Comment, be sure to
  # update the return value of this method accordingly.
  def valid_comment_attributes
    {
        :comment => "Commentcomment"
    }
  end

  def valid_post_attributes
    {
        :post => "Postpost"
    }
  end

  def valid_user_attributes
    {
        :name => "admin",
        :password_digest => "admin_pass",
        :is_admin => true
    }
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommentsController. Be sure to keep this updated too.
  def valid_session
    {
        :user_id => 1
    }
  end

  describe "GET index" do
    it "assigns all comments as @comments" do
      User.create! valid_user_attributes
      Post.create! valid_post_attributes
      comment = Comment.create! valid_comment_attributes
      get :index, {}, valid_session
      assigns(:comments).should eq([comment])
    end
  end

  describe "GET show" do
    it "assigns the requested comment as @comment" do
      User.create! valid_user_attributes
      Post.create! valid_post_attributes
      comment = Comment.create! valid_comment_attributes
      get :show, {:id => comment.to_param}, valid_session
      assigns(:comment).should eq(comment)
    end
  end

  describe "GET new" do
    it "assigns a new comment as @comment" do
      User.create! valid_user_attributes
      Post.create! valid_post_attributes
      get :new, {}, valid_session
      assigns(:comment).should be_a_new(Comment)
    end
  end

  describe "GET edit" do
    it "assigns the requested comment as @comment" do
      User.create! valid_user_attributes
      Post.create! valid_post_attributes
      comment = Comment.create! valid_comment_attributes
      get :edit, {:id => comment.to_param}, valid_session
      assigns(:comment).should eq(comment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Comment" do
        User.create! valid_user_attributes
        a_post = Post.create! valid_post_attributes
        expect {
          post :create, {:comment => valid_comment_attributes, :post_id => a_post.id}, valid_session
        }.to change(Comment, :count).by(1)
      end

      it "assigns a newly created comment as @comment" do
        User.create! valid_user_attributes
        a_post = Post.create! valid_post_attributes
        post :create, {:comment => valid_comment_attributes, :post_id => a_post.id}, valid_session
        assigns(:comment).should be_a(Comment)
        assigns(:comment).should be_persisted
      end

      it "redirects to the post for the created comment" do
        User.create! valid_user_attributes
        a_post = Post.create! valid_post_attributes
        post :create, {:comment => valid_comment_attributes, :post_id => a_post.id}, valid_session
        #response.should redirect_to(Comment.last)
        response.should redirect_to(a_post)
      end
    end

    #No invalid params for comments (they can be null)
    #describe "with invalid params" do
    #  it "assigns a newly created but unsaved comment as @comment" do
    #    # Trigger the behavior that occurs when invalid params are submitted
    #    Comment.any_instance.stub(:save).and_return(false)
    #    post :create, {:comment => {}}, valid_session
    #    assigns(:comment).should be_a_new(Comment)
    #  end
    #
    #  it "re-renders the 'new' template" do
    #    # Trigger the behavior that occurs when invalid params are submitted
    #    Comment.any_instance.stub(:save).and_return(false)
    #    post :create, {:comment => {}}, valid_session
    #    response.should render_template("new")
    #  end
    #end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested comment" do
        User.create! valid_user_attributes
        Post.create! valid_post_attributes
        comment = Comment.create! valid_comment_attributes
        # Assuming there are no other comments in the database, this
        # specifies that the Comment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Comment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => comment.to_param, :comment => {'these' => 'params'}}, valid_session
      end

      #TODO: these seem to try to route to comment_url, instead of posts_comment_url??
      #it "assigns the requested comment as @comment" do
      #  User.create! valid_user_attributes
      #  a_post = Post.create! valid_post_attributes
      #  comment = Comment.create! valid_comment_attributes
      #  put :update, {:id => comment.to_param, :comment => valid_comment_attributes}, valid_session
      #  assigns(:comment).should eq(comment)
      #end
      #
      #it "redirects to the post for the comment" do
      #  User.create! valid_user_attributes
      #  a_post = Post.create! valid_post_attributes
      #  comment = Comment.create! valid_comment_attributes
      #  put :update, {:id => comment.to_param, :comment => valid_comment_attributes}, valid_session
      #  response.should redirect_to(a_post)
      #end
    end

    #No invalid parameters (comments can be null)
    #describe "with invalid params" do
    #  it "assigns the comment as @comment" do
    #    comment = Comment.create! valid_comment_attributes
    #    # Trigger the behavior that occurs when invalid params are submitted
    #    Comment.any_instance.stub(:save).and_return(false)
    #    put :update, {:id => comment.to_param, :comment => {}}, valid_session
    #    assigns(:comment).should eq(comment)
    #  end
    #
    #  it "re-renders the 'edit' template" do
    #    comment = Comment.create! valid_comment_attributes
    #    # Trigger the behavior that occurs when invalid params are submitted
    #    Comment.any_instance.stub(:save).and_return(false)
    #    put :update, {:id => comment.to_param, :comment => {}}, valid_session
    #    response.should render_template("edit")
    #  end
    #end
  end

  describe "DELETE destroy" do
    it "destroys the requested comment" do
      User.create! valid_user_attributes
      Post.create! valid_post_attributes
      comment = Comment.create! valid_comment_attributes
      expect {
        delete :destroy, {:id => comment.to_param}, valid_session
      }.to change(Comment, :count).by(-1)
    end

    it "redirects to the comments list" do
      User.create! valid_user_attributes
      Post.create! valid_post_attributes
      comment = Comment.create! valid_comment_attributes
      delete :destroy, {:id => comment.to_param}, valid_session
      response.should redirect_to(posts_url)
    end
  end

end
